version: '3'

services:

  scrapper:
    container_name: scrapper
    build: 
      context: . 
      dockerfile: Dockerfile
    command:  bash start.sh 
    network_mode: host
    # ports:
    #        - 6800:6800
    restart: always
    depends_on: 
        - postgres
    volumes:
      - /var/log/web_crawler:/usr/src/app/logs/immo_crawl
   

  postgres:
    build:
      context: . 
      dockerfile: Dockerfile.psql
    container_name: postgres
    environment:
       POSTGRES_PASSWORD: ${CRAWL_DB_PASSWORD:?set CRAWL_DB_PASSWORD in .env}
       POSTGRES_DB: eva_db
    network_mode: host
    # ports:
    #   - 5432:5432
    restart: always
  elasticsearch:
      image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
      environment:
          - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
          - "discovery.type=single-node"
      ports:
          - "9200:9200"
      volumes:
          - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
      image: "docker.elastic.co/kibana/kibana:7.2.0"
      ports:
          - "5601:5601"

  filebeat:
      image: "docker.elastic.co/beats/filebeat:7.2.0"
      user: root
      volumes:
          - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
          - /var/log/web_crawler:/usr/web_crawler
          - /var/lib/docker:/var/lib/docker:ro
          - /var/run/docker.sock:/var/run/docker.sock
          

volumes:
  elasticsearch_data: